quickdesktop is high level gtk based library to create desktop
applications. With few configurations and simple plugin files in
text format, it is possible to create a desktop application.

A typical desktop application consists of a tool frame with 
menubar and/or commandbar with a working space below. Typical
user input components like string/numeric input , boolean, radio,
dropbox, file choosing etc. are required. 

quickdesktop supports creation of menus/commandbar and a 
customizable toolframe using plugin files. These plugin files
are in human readable format. It also supports typical user 
interface creation using various parameters to control them. 
Following philosophy used by glade, it is possible to create 
automated UI creation. But configuration files generated by 
glade for UI creation are xml files. This becomes cumbersome 
to manage by humans. quickdesktop consists of quickui component 
which makes the above mentioned process through human readable 
file format.

To create a desktop application using quickdesktop you need
to download quickdesktop library. Add it to PYTHONPATH. i.e.
add line similar to this in your .bashrc file

$export PYTHONPATH=$PYTHONPATH:$HOME/programming/work/rep/

here $HOME/programming/work/rep/ is the directory in which 
source directory "quickdesktop" lies.


also qdesktop.py file in system path.
on linux you can do this by adding following line in .bashrc file

$export $PATH=$PATH:$HOME/programming/work/rep/quickdesktop.

Now you are ready to use quickdesktop library to create a 
desktop tool.

to create a new desktop tool with name sample run following command.

$qdesktop.py create sample
Creating folder structure
Creating plugins
Creating configurations
Creating resources

in current working directory you will see a new folder called "sample"
just browse through it. you will see following structure.
+ sample
  + config
  + plugins
  + resources
  sample

here + signs indicate that they are folders. you can run this executable called
sample. Your sample desktop is up!

For further progress wait for a tutorial! Or if you are smart, just go through 
plugins directory and you might understand how to proceed further.
